### ISSUE TITLE
Gantt error on applyState

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1214]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=14693&p=74732)

Hi!

I'm testing a prerelease of 2.1.7 and I found that Gantt.applyState() does not like state objects deserialized from JSON... Here are the steps:

Load any gantt, as long as it's the version I'm using
Set the gantt instance into the window
Run this command in the console:
```
gantt.applyState(JSON.parse(JSON.stringify(gantt.getState())));

```

Result:
Error: date.getTime is not a function

Expected result:
The grid state is restored.

Additional details:
This works fine in 2.1.6
I'm aware this may not be a regression per se but an improper handling of the serialization on my side.

Regards
