### ISSUE TITLE
Race condition and `me.nextAnimationFrame is not a function` error

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#2480]
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=16807&p=83601#p83601)

After upgrading from v4.0.6 to v4.0.8 of bryntum, I occasionally get the following error: TypeError: me.nextAnimationFrame is not a function. This seems to happen when I destory the schedule engine before it even has a chance to render (I use bryntum with react and this can happen from various prop changes)

Disabling visibleDate in the scheduler config "fixes" this (As a fix, I use an event listener on load that checks to see if the scheduler is not destroyed first)

This happens in TimelineScroll.js:94

```
>
me {
    isDestroying: true,
    isDestroyed: true,
    destroy: ƒ,
    …
}
```

Stack trace:

```
scrollToCoordinate
http: //localhost/static/js/0.chunk.js:355614:15
    355611 |
    355612 | await me.timeAxisSubGrid.scrollable.scrollIntoView(target,
        options
    ); // Horizontal scroll is triggered on next frame in SubGrid.js, view is not up to date yet. Resolve on next frame
355613 |
    >
    355614 |
    return me.nextAnimationFrame(); |
^
355615 |
} //endregion
355616 | //region Relative scrolling
    355617 |
// These methods are important to users because although they are mixed into the top level Grid/Scheduler,
```
