### ISSUE TITLE
[TypeScript] Problems after upgrade from 5.5.3 to 6.0.2

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#10268]
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=30884&p=156813#p156813)

Hi

I have upgraded Bryntum SchedulerPro vom 5.5.3 to 6.0.2.
Now, I have a problem, for which I did not find a solution.

Here is the Code with the Problem:

```
        new Tooltip({
            forSelector: '#employeeScheduler .b-sch-header-timeaxis-cell',
            html: 'Planungsinfos zum aktuellen Tag',
            listeners: {
                beforeShow: (props) => {
                    const { source: tip } = props;
                    var classList = Array.from(tip.triggeredByEvent.target.classList as DOMTokenList);

                if (!classList.some(x => x == "b-sch-header-timeaxis-cell") || classList.some(x => x.startsWith("b-sch-dayheadercell-"))) {
                    const date = this.scheduler1.timeAxis.getDateFromTick(tip.activeTarget.dataset.tickIndex);
                    return this.calculateStatisticsForDay(date, tip);
                }
                return this.calculateStatisticsForWeek(tip);
            }
        }
    });
```

This are the two problems:

Error: Property 'classList' does not exist on type 'EventTarget'.
var classList = Array.from(tip.triggeredByEvent.target.classList as DOMTokenList);
                                                               
Error: Argument of type 'string' is not assignable to parameter of type 'number'.
const date = this.scheduler1.timeAxis.getDateFromTick(tip.activeTarget.dataset.tickIndex);

then I have a third problem:

```
        let store = this.scheduler1.resourceStore;
        store.sort({
            fn: (recordA, recordB) => {
                // -1 = A < B
                //  1 = A > B
                //  0 = A = B

            let lenA = recordA.events/*.filter(x => x.data.role == 3)*/.length;
            let lenB = recordB.events/*.filter(x => x.data.role == 3)*/.length;
            ....
            ....
            
```

Error:

error TS2345: Argument of type '{ fn: (recordA: any, recordB: any) => any; }' is not assignable to parameter of type 'string | Function | Sorter | Sorter[]'.
  Type '{ fn: (recordA: any, recordB: any) => any; }' is not assignable to type 'string'.

Which type do I need there now to access the resource-records in my sort-logic?

Thank you very much for your support.

Best Regards
Thomas

**Comment by matsbryntse** [comment]
"then I have a third problem:" this is already reported and fixed here https://github.com/bryntum/bryntum-suite/pull/12451

**Comment by matsbryntse** [comment]
The getDateFromTick correctly expects Number. Your issue is that dataset.tickIndex is always a string (DOM spec). You need to convert: parseInt(dataset.tickIndex) or Number(dataset.tickIndex). This is not a bug in our types.
